### ISSUE TITLE
Comments (in Cookie) ignores spaces

### ISSUE THREAD

**Issue by joker234** [nnev/yarpnarp#1]
In https://github.com/nnev/yarpnarp/blob/master/main.go#L103 is an issue. I think spaces should be escaped in the cookie.

**Comment by Merovius** [comment]
Ich glaube, die beste Lösung ist, ein struct anzulegen für alle Dinge, die in das cookie sollten, das dann mit json zu encoden, das json dann base64 zu kodieren und das im Cookie zu speichern

**Comment by joker234** [comment]
Eine Idee wann das online geht?

**Comment by koebi** [comment]
Ist online :)
